export enum MapObjectType {
	SCHOOL = 'school',
	HOSPITAL = 'hospital',
	STORE = 'store',
	CINEMA = 'cinema',
	MUNICIPAL_INSTITUTION = 'municipal_institution',
	PHARMACY = 'pharmacy',
	SUPERMARKET = 'supermarket',
	SHOPPING_MALL = 'shopping_mall',
	SHOP = 'shop',
	MAINTENANCE_INSTITUTION = 'maintenance_institution',
	KINDERGARTEN = 'kindergarten',
	COLLEGE = 'college',
	UNIVERSITY = 'university',
	THEATER = 'theater',
	RESTAURANT = 'restaurant',
	STATION = 'station',
	APARTMENT_BUILDING = 'apartment_building',
	PARK = 'park',
	GAS_STATION = 'gas_station',
	PLAYGROUND = 'playground',
	SPORTS_AREA = 'sports_area',
	BANK = 'bank',
	SOCIAL_INSTITUTION = 'social_institution',
	POST_OFFICE = 'post_office',
}

export enum StreetType {
	STREET = 'street',
	PROSPECT = 'prospect',
}
